#sdk: "C:/RhoStudio/ruby/lib/ruby/gems/1.8/gems/rhodes-3.3.2"
sdkversion: 3.3.2
name: rcmonitor
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.rcmonitor
  BundleURLScheme: rcmonitor
wp:
  productid: '526e3f81-9353-012f-d4cb-70f1a1bddd12'
symbian:
  uid: '0xe7a5c784'
android:
  version: 2.1

extensions: ["json", "another-extension"]
